image: python:3.11

services:
  - postgres:14

variables:
  POSTGRES_DB: test_db
  POSTGRES_USER: test_user
  POSTGRES_PASSWORD: test_pass
  POSTGRES_HOST: postgres
  DJANGO_SETTINGS_MODULE: hh_api.settings

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - venv/

backend-tests:
  stage: test
  script:
    - apt-get update && apt-get install -y netcat-openbsd curl
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install pytest pytest-django pytest-cov
    - until nc -z postgres 5432; do echo "Waiting for Postgres..."; sleep 1; done
    - python manage.py migrate
    - export PYTHONPATH="${PYTHONPATH}:$(pwd)"
    - pytest --cov=. --cov-report=xml --junitxml=pytest-report.xml
    - bash <(curl -s https://codecov.io/bash)
  artifacts:
    when: always
    reports:
      junit: pytest-report.xml
    paths:
      - pytest-report.xml
      - coverage.xml
