version: "3.8"
services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - 8000:8000
    image: application:hauntedhotel
    command: gunicorn hh_api.wsgi:application --bind 0.0.0.0:8000
