version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: application:hauntedhotel
    command: gunicorn hauntedhotel_api.wsgi:application --bind 0.0.0.0:8000
