# Generated by Django 5.1.4 on 2025-01-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='uploads/default-room.png', upload_to='uploads/rooms/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wing',
            name='image_url',
            field=models.ImageField(blank=True, default='uploads/default-wing.png', null=True, upload_to='uploads/wings'),
        ),
    ]
